name: test
run-name: ${{ github.actor }}
on: [pull_request]
jobs:
  test-compilation:
    runs-on: windows-latest
    steps:
      
        - name: Setup python
          uses: actions/setup-python@v6.2.0
  
        - name: Setup Vulkan SDK
          run: curl -O https://sdk.lunarg.com/sdk/download/latest/windows/vulkan_sdk.exe
  
        - name: Checkout PR
          uses: actions/checkout@v6.0.2

        - name: configure repo
          run: py ${GITHUB_WORKSPACE}/scripts/clang_withtests.py
          
        - name: build repo
          run: cmake --build ${GITHUB_WORKSPACE}/build --config Debug
